-- ================================================================
-- KanpurCabs: Supabase Database Seed Data
-- ================================================================

-- 1. SEED CARS
INSERT INTO public.cars (name, slug, category, brand, model, year, seats, doors, luggage, transmission, fuel_type, ac, description, features, price_per_km, price_per_day, price_per_hour, minimum_charge, driver_allowance, night_charge, is_available, is_featured, sort_order)
VALUES
('Maruti Suzuki Swift', 'maruti-suzuki-swift', 'hatchback', 'Maruti Suzuki', 'Swift', 2023, 4, 4, 2, 'manual', 'petrol', true, 'The Maruti Suzuki Swift is a fuel-efficient hatchback perfect for local Kanpur city travel, shopping, and short commutes.', ARRAY['Air Conditioning', 'Power Steering', 'Music System', 'USB Charging', 'Central Locking'], 9, 1800, 250, 500, 300, 200, true, true, 1),
('Maruti Suzuki Dzire', 'maruti-suzuki-dzire', 'sedan', 'Maruti Suzuki', 'Dzire', 2023, 4, 4, 3, 'manual', 'petrol', true, 'The Maruti Suzuki Dzire is the preferred sedan for airport transfers and outstation journeys with comfortable seating and spacious boot space.', ARRAY['Air Conditioning', 'Power Steering', 'Music System', 'USB Charging', 'Central Locking', 'Airbags', 'Rear AC Vents'], 10, 2000, 280, 600, 300, 250, true, true, 2),
('Hyundai Aura', 'hyundai-aura', 'sedan', 'Hyundai', 'Aura', 2023, 4, 4, 3, 'manual', 'petrol', true, 'Stylish and refined sedan offering exceptional passenger comfort for business and leisure travel across Kanpur.', ARRAY['Air Conditioning', 'Power Steering', 'Touchscreen Infotainment', 'USB Charging', 'Central Locking', 'Airbags'], 10, 2000, 280, 600, 300, 250, true, false, 3),
('Toyota Innova Crysta', 'toyota-innova-crysta', 'suv', 'Toyota', 'Innova Crysta', 2023, 6, 4, 4, 'manual', 'diesel', true, 'The gold standard for family vacations and group outstation trips. Unmatched comfort, captain seats, and powerful performance.', ARRAY['Air Conditioning', 'Captain Seats', 'Touchscreen Infotainment', 'USB Charging', 'Central Locking', 'Airbags', 'Rear AC Vents', 'Cruise Control'], 16, 3500, 450, 1000, 400, 300, true, true, 4),
('Mahindra Scorpio N', 'mahindra-scorpio-n', 'suv', 'Mahindra', 'Scorpio N', 2023, 7, 4, 3, 'manual', 'diesel', true, 'Rugged 7-seater SUV with high ground clearance, built for comfortable highway road trips and pilgrimage tours from Kanpur.', ARRAY['Air Conditioning', 'Music System', 'USB Charging', 'Central Locking', 'Airbags', 'Rear AC Vents'], 14, 3000, 400, 800, 400, 300, true, true, 5),
('Hyundai Creta', 'hyundai-creta', 'suv', 'Hyundai', 'Creta', 2024, 5, 4, 3, 'automatic', 'petrol', true, 'Modern premium compact SUV with automatic transmission and panoramic sunroof for executive comfort.', ARRAY['Air Conditioning', 'Touchscreen Infotainment', 'USB Charging', 'Airbags', 'Panoramic Sunroof', 'Ventilated Seats'], 14, 3200, 420, 900, 350, 300, true, false, 6),
('Toyota Fortuner', 'toyota-fortuner', 'luxury', 'Toyota', 'Fortuner', 2023, 7, 4, 4, 'automatic', 'diesel', true, 'Premium luxury SUV designed for VIP delegations, wedding entourages, and high-profile corporate travel in Kanpur.', ARRAY['Air Conditioning', 'Leather Seats', 'Touchscreen Infotainment', 'USB Charging', 'Airbags', 'Cruise Control', '4WD', 'Power Tailgate'], 20, 5000, 650, 1500, 500, 400, true, true, 7),
('Force Tempo Traveller', 'force-tempo-traveller', 'tempo_traveller', 'Force', 'Tempo Traveller', 2023, 12, 2, 6, 'manual', 'diesel', true, 'Spacious 12-seater mini bus with pushback seats and dual AC, ideal for wedding guests, corporate outings, and family pilgrimages.', ARRAY['Air Conditioning', 'Pushback Seats', 'Music System', 'USB Charging', 'Curtains', 'Luggage Carrier', 'First Aid Kit'], 22, 5500, 700, 2000, 500, 400, true, true, 8)
ON CONFLICT (slug) DO NOTHING;

-- 2. SEED SERVICES
INSERT INTO public.services (name, slug, tagline, description, icon, features, is_active, sort_order, meta_title, meta_description)
VALUES
('Local Car Rental', 'local-car-rental', 'Hourly car rental with professional driver for Kanpur city travel', 'Explore Kanpur comfortably with our hourly car rental service. Whether you need a car for shopping, business meetings, hospital visits, or city errands, our professional chauffeurs are at your service.', 'Clock', ARRAY['Flexible hourly packages (4hr/40km, 8hr/80km, 12hr/120km)', 'Professional verified drivers', 'AC cars available', 'All Kanpur areas covered', 'Corporate billing available'], true, 1, 'Local Car Rental in Kanpur | Hourly Cab Booking', 'Book affordable hourly car rental in Kanpur with professional drivers. 4hr, 8hr, 12hr packages available.'),
('Outstation Cabs', 'outstation-cab', 'Comfortable one-way & round-trip cabs from Kanpur', 'Travel beyond Kanpur with our reliable outstation cab service. One-way drops and round trips to Lucknow, Agra, Varanasi, Delhi, Prayagraj, Ayodhya, and 100+ destinations.', 'Navigation', ARRAY['One-way and round-trip available', 'Transparent per-km pricing', 'All-inclusive fares (fuel + driver)', 'Multiple vehicle options', 'Multi-city trips supported'], true, 2, 'Outstation Cabs from Kanpur | One-Way & Round Trip', 'Book outstation cabs from Kanpur to Lucknow, Agra, Varanasi, Delhi & more.'),
('Airport Transfer', 'airport-transfer', 'Reliable pickup & drop to Kanpur Airport (Chakeri)', 'Never miss a flight with our punctual airport transfer service. We provide comfortable pickups and drops to Kanpur Airport (Chakeri) with flight tracking and meet & greet service.', 'Plane', ARRAY['Kanpur Airport (Chakeri) coverage', 'Flight tracking for pickups', 'Meet & greet service', 'Fixed pricing, no surge', 'Available 24/7'], true, 3, 'Airport Transfer Kanpur | Cab to Kanpur Airport Chakeri', 'Book reliable airport transfer in Kanpur. Pickup and drop to Kanpur Airport.'),
('Railway Station Transfer', 'railway-station-transfer', 'Comfortable transfers to/from Kanpur railway stations', 'Get hassle-free transfers to and from Kanpur Central (CNB), Kanpur Anwarganj, and Govindpuri stations with punctual and comfortable cab service.', 'Train', ARRAY['Kanpur Central, Anwarganj, Govindpuri covered', 'Train tracking for pickups', 'Fixed pricing', 'All city areas covered', 'Available 24/7'], true, 4, 'Railway Station Transfer Kanpur | Cab to Kanpur Central', 'Book comfortable railway station transfers in Kanpur.'),
('Corporate Car Rental', 'corporate-car-rental', 'Dedicated car rental solutions for businesses in Kanpur', 'Professional corporate car rental services for businesses in Kanpur. Employee transport, client pickups, event logistics, and monthly retainer packages with GST billing.', 'Building', ARRAY['Dedicated account manager', 'Monthly retainer packages', 'GST billing & invoicing', 'Employee transport solutions', 'Premium fleet for executives'], true, 5, 'Corporate Car Rental Kanpur | Business Cab Service', 'Professional corporate car rental in Kanpur with GST billing.'),
('Wedding Car Rental', 'wedding-car-rental', 'Luxury decorated cars for your special day in Kanpur', 'Make your wedding day extra special with our premium wedding car rental service. Beautifully decorated luxury cars for bride and groom, baraat processions, and guest transport.', 'Heart', ARRAY['Luxury car decoration', 'Baraat car arrangements', 'Guest transport (Tempo Travellers)', 'Multi-car packages', 'Customized decoration'], true, 6, 'Wedding Car Rental Kanpur | Luxury Wedding Cars', 'Book luxury wedding car rental in Kanpur.')
ON CONFLICT (slug) DO NOTHING;

-- 3. SEED TOUR PACKAGES
INSERT INTO public.tour_packages (name, slug, tagline, description, duration, distance, destinations, highlights, price, price_label, inclusions, exclusions, is_active, is_featured, sort_order)
VALUES
('Kanpur Half-Day City Tour', 'kanpur-half-day-city-tour', 'Explore Kanpur top attractions in half a day', 'Discover the best of Kanpur in just 4 hours. Visit the iconic JK Temple, the historic Allen Forest Zoo, serene Moti Jheel, and the beautiful Nana Rao Park.', '4 Hours', '~30 km', ARRAY['JK Temple', 'Allen Forest Zoo', 'Moti Jheel', 'Nana Rao Park'], ARRAY['Visit architecturally stunning JK Temple', 'Explore one of India oldest zoos', 'Enjoy serene Moti Jheel lake', 'Learn history at Nana Rao Park'], 1500, 'Starting from ₹1,500', ARRAY['AC Sedan car', 'Professional driver', 'Fuel charges', 'Toll & parking', 'Driver allowance'], ARRAY['Entry tickets', 'Personal expenses', 'Food & beverages'], true, true, 1),
('Kanpur Full-Day City Tour', 'kanpur-full-day-city-tour', 'Complete Kanpur sightseeing experience', 'Experience everything Kanpur has to offer in a comprehensive full-day tour covering temples, parks, historical sites, shopping areas, and the famous Ganga ghats.', '8 Hours', '~60 km', ARRAY['JK Temple', 'Allen Forest Zoo', 'Moti Jheel', 'Kanpur Memorial Church', 'Green Park Stadium', 'Bithoor'], ARRAY['Complete city sightseeing', 'Visit all major temples and landmarks', 'Explore historical monuments', 'Green Park Cricket Stadium', 'Evening at Bithoor Ganga ghats'], 2500, 'Starting from ₹2,500', ARRAY['AC Sedan car', 'Professional driver', 'Fuel charges', 'Toll & parking', 'Driver allowance', 'Water bottles'], ARRAY['Entry tickets', 'Personal expenses', 'Food & beverages', 'Guide charges'], true, true, 2),
('Bithoor Pilgrimage Tour', 'bithoor-pilgrimage-tour', 'Sacred pilgrimage to the holy town of Bithoor', 'Visit the sacred town of Bithoor on the banks of River Ganges. Explore ancient temples, sacred ghats, and historical sites associated with Lord Brahma and Sage Valmiki.', '5 Hours', '~40 km', ARRAY['Brahmavart Ghat', 'Valmiki Ashram', 'Patthar Ghat', 'Siddhidham Ashram'], ARRAY['Visit sacred Brahmavart Ghat', 'Explore ancient Valmiki Ashram', 'Patthar Ghat architecture', 'Spiritual peace at Siddhidham Ashram'], 1800, 'Starting from ₹1,800', ARRAY['AC Sedan car', 'Professional driver', 'Fuel charges', 'Toll & parking', 'Driver allowance'], ARRAY['Pooja charges', 'Personal expenses', 'Food & beverages', 'Boat ride charges'], true, true, 3),
('Ayodhya-Prayagraj Pilgrimage', 'ayodhya-prayagraj-pilgrimage', 'Sacred 2-day pilgrimage to Ayodhya and Prayagraj', 'Embark on a sacred 2-day pilgrimage from Kanpur to Ayodhya and Prayagraj. Visit the magnificent Ram Mandir in Ayodhya and holy Triveni Sangam in Prayagraj.', '2 Days / 1 Night', '~450 km', ARRAY['Ayodhya Ram Mandir', 'Hanuman Garhi', 'Saryu River Ghat', 'Prayagraj Triveni Sangam', 'Anand Bhawan'], ARRAY['Visit newly built Ram Mandir in Ayodhya', 'Blessings at Hanuman Garhi', 'Evening Aarti at Saryu River', 'Holy dip at Triveni Sangam in Prayagraj'], 6500, 'Starting from ₹6,500', ARRAY['AC Sedan car for both days', 'Professional driver', 'Fuel charges', 'Toll charges', 'Driver allowance & accommodation'], ARRAY['Hotel accommodation for guests', 'Pooja items', 'Food & beverages', 'Personal expenses'], true, true, 4)
ON CONFLICT (slug) DO NOTHING;

-- 4. SEED OUTSTATION DESTINATIONS
INSERT INTO public.destinations (name, slug, description, distance, distance_km, duration, highlights, hatchback_price, sedan_price, suv_price, tempo_price, route_via, toll_info, best_time, is_popular, is_active, sort_order)
VALUES
('Lucknow', 'kanpur-to-lucknow', 'Travel to the City of Nawabs. Known for rich heritage, Bara Imambara, Rumi Darwaza, and world-famous Awadhi cuisine.', '~80 km', 80, '~1.5 hours', ARRAY['Bara Imambara', 'Rumi Darwaza', 'Hazratganj', 'British Residency', 'Awadhi Cuisine'], 2000, 2500, 3500, 5000, 'via NH-27 (Lucknow-Kanpur Highway)', '1-2 toll plazas (~₹100-150)', 'October to March', true, true, 1),
('Agra', 'kanpur-to-agra', 'Visit the iconic Taj Mahal, one of the Seven Wonders of the World, along with Agra Fort and Fatehpur Sikri.', '~280 km', 280, '~4.5 hours', ARRAY['Taj Mahal', 'Agra Fort', 'Fatehpur Sikri', 'Mehtab Bagh'], 4500, 5500, 7500, 10000, 'via NH-19 (Agra-Lucknow Expressway)', '3-4 toll plazas (~₹400-500)', 'October to March', true, true, 2),
('Varanasi', 'kanpur-to-varanasi', 'Experience the spiritual capital of India with its ancient ghats, Kashi Vishwanath temple, and evening Ganga Aarti.', '~330 km', 330, '~5.5 hours', ARRAY['Dashashwamedh Ghat', 'Kashi Vishwanath Temple', 'Ganga Aarti', 'Assi Ghat', 'Sarnath'], 5500, 6500, 9000, 12000, 'via NH-19 / NH-31', '4-5 toll plazas (~₹500-600)', 'October to March', true, true, 3),
('Delhi', 'kanpur-to-delhi', 'Travel comfortably to the capital of India. Explore historic monuments, markets, and business hubs.', '~440 km', 440, '~6.5 hours', ARRAY['India Gate', 'Red Fort', 'Qutub Minar', 'Connaught Place'], 6500, 8000, 11000, 15000, 'via Agra-Lucknow & Yamuna Expressway', '5-6 toll plazas (~₹700-800)', 'October to March', true, true, 4),
('Prayagraj', 'kanpur-to-prayagraj', 'Visit the holy city at the confluence of Ganges, Yamuna, and Saraswati for Triveni Sangam and historic sites.', '~200 km', 200, '~3.5 hours', ARRAY['Triveni Sangam', 'Akshay Vat', 'Anand Bhawan', 'Allahabad Fort'], 3500, 4000, 5500, 8000, 'via NH-19', '2-3 toll plazas (~₹200-300)', 'October to March', true, true, 5),
('Ayodhya', 'kanpur-to-ayodhya', 'Pilgrimage to the birthplace of Lord Ram. Visit the grand Ram Mandir and sacred ghats of Saryu.', '~230 km', 230, '~4 hours', ARRAY['Ram Mandir', 'Hanuman Garhi', 'Kanak Bhawan', 'Saryu River'], 3800, 4500, 6500, 9000, 'via NH-27', '2-3 toll plazas (~₹250-350)', 'October to March', true, true, 6)
ON CONFLICT (slug) DO NOTHING;

-- 5. SEED FAQS
INSERT INTO public.faqs (question, answer, category, is_active, sort_order)
VALUES
('How do I book a car in Kanpur?', 'Booking a car with KanpurCabs is seamless! Fill out the booking form on our website, call our 24/7 helpline at +91 98765 43210, or message us on WhatsApp for instant confirmation.', 'booking', true, 1),
('What types of vehicles are available in your fleet?', 'We offer Hatchbacks (Swift), Sedans (Dzire, Aura), SUVs (Innova Crysta, Scorpio N, Creta), Luxury SUVs (Fortuner), and 12-seater Tempo Travellers. All vehicles are air-conditioned and sanitized.', 'general', true, 2),
('What are your outstation trip fare inclusions?', 'Outstation fares include fuel, vehicle rent, and driver allowance. For one-way trips, tolls are typically included. For round-trip bookings, highway toll taxes and parking are paid at actuals.', 'pricing', true, 3),
('Do you provide airport and railway station pickup/drops?', 'Yes, we provide 24/7 dedicated airport transfers to Kanpur Airport (Chakeri) and all railway terminals including Kanpur Central (CNB) and Govindpuri with zero surge pricing.', 'airport', true, 4),
('Are your drivers background-verified?', 'Every driver partner undergoes comprehensive 7-stage vetting, including police background check, driving license verification, Aadhaar verification, and highway safety training.', 'safety', true, 5)
ON CONFLICT DO NOTHING;

-- 6. SEED SITE SETTINGS
INSERT INTO public.site_settings (key, value)
VALUES
('business_name', '"KanpurCabs"'::jsonb),
('business_phone', '"+91 98765 43210"'::jsonb),
('business_email', '"info@kanpurcabs.com"'::jsonb),
('business_whatsapp', '"+919876543210"'::jsonb),
('business_address', '"Civil Lines, Kanpur, Uttar Pradesh 208001"'::jsonb)
ON CONFLICT (key) DO NOTHING;
